### ISSUE TITLE
When using Ctrl + C in client, the server will crash (BrokenPipe)

### ISSUE THREAD

**Issue by randomdev4578** [Strawberry-Foundations/strawberry-chat#1]
As the title says, if you use Ctrl + C in the client, the server crashes with the BrokenPipe error message. Occurs with v1.7.0 Beta 2 and 3

**Comment by Juliandev02** [comment]
This is already known in your team. We will work on it.

**Comment by matteodev8** [comment]
@Juliandev02 https://docs.python.org/3/library/signal.html#note-on-sigpipe

**Comment by Juliandev02** [comment]
Finally fixed this issue with Commit https://github.com/Strawberry-Foundations/strawberry-chat/commit/7e70d83491c5a6cd83abf805fd89f94ba4d450f5
