### ISSUE TITLE
Ich hab durchfall

### ISSUE THREAD

**Issue by ElectroGehirn** [Strawberry-Foundations/strawberry-chat#132]
### Describe the bug

Ich hab beim china typ gegessen 

### Steps to reproduce

```bash
Beim china typ essen
```

### The Error Text/Stacktrace

ERROR-Toilette: KLOPAPIER OVERFLOW
ERROR-Toilette: SCHEIßE OVERFLOW

### Client Report (Run "python client.py --gen-report")

k

### Chat Program

Client

### The version of Strawberry Chat you used

All

### Python Version

0.0.1 Beta

### Operating System

other

### Operating System Version

0

### Used Operating System (Only fill when selected "other")

Sexy grandmaOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This bug isn't fixed in the latest version of Strawberry Chat (including git)

**Comment by Juliandev02** [comment]
This bug has been resolved with the Rust Rewrite.

**Comment by ElectroGehirn** [comment]
omg thank you
