### ISSUE TITLE
UTF-8 only protection

### ISSUE THREAD

**Issue by Juliandev02** [Strawberry-Foundations/strawberry-chat#14]
A protection that you can only send messages that are UTF-8 compliant. If not, the user should be kicked

**Comment by Paddyk45** [comment]
How is it critical??

**Comment by Juliandev02** [comment]
> How is it critical??

This could crash the server if you send through a non-UTF-8 message (like a file, what someone has already done)

**Comment by Juliandev02** [comment]
This issue is irrelevant because "UTF-8" protection already exists. 
-> If the server receives a non-UTF-8 compatible message, the user of the non-UTF-8 compatible message will be kicked. This is an automatic procedure for our security system.
