### ISSUE TITLE
Codacy reporting 1,978 security issues

### ISSUE THREAD

**Issue by matteodev8** [Strawberry-Foundations/strawberry-chat#28]
### Describe the bug

No rules have been setup for the workflow which results in "invalid" reports

### Steps to reproduce

```bash
Set up Codacy without any rules
```

### Chat Program

Client

### The version of Strawberry Chat you used

-

### Python Version

-

### Operating System

other

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This bug isn't fixed in the latest version of Strawberry Chat (including git)

**Comment by Juliandev02** [comment]
I/we would appreciate it if you could possibly post the rules for Codacy as soon as possible. Thank you!

**Comment by Juliandev02** [comment]
Codacy has been deleted from this repositiory. Closing issue
