### ISSUE TITLE
Fix code scanning alert - Overly permissive regular expression range

### ISSUE THREAD

**Issue by Juliandev02** [Strawberry-Foundations/strawberry-chat#38]
Tracking issue for:
- [ ] https://github.com/Strawberry-Foundations/strawberry-chat/security/code-scanning/2006

**Comment by Juliandev02** [comment]
I dont think is is a important security warning. This alert is not relevant

**Comment by matteodev8** [comment]
u stupid

**Comment by Juliandev02** [comment]
> u stupid

why?
