### ISSUE TITLE
Setting the username and sending a message allow bash commands to be executed in the server host

### ISSUE THREAD

**Issue by Paddyk45** [Strawberry-Foundations/strawberry-chat#4]
Using message:
![Screenshot_20230812-095554_Termux.jpg](https://github.com/Strawberry-Foundations/strawberry-chat/assets/73178245/f4ad6c8e-eff6-4938-8b11-9e06a446f1f4)

Using username
![Screenshot_20230812-100110_Termux.jpg](https://github.com/Strawberry-Foundations/strawberry-chat/assets/73178245/fb981f9d-f827-4fba-bb48-8c6e6c39cb81)

**Comment by Juliandev02** [comment]
Thank you for your bug report. We will try to fix this as soon as possible. Your bug has been added to our TODO list (see project [Strawberry Chat](https://github.com/orgs/Strawberry-Foundations/projects/1)). 

If you have enough time, could you possibly try to check Strawberry Chat for more injections? 
For example SQL injection for messages, username, or nickname? Thanks a lot!

**Comment by Paddyk45** [comment]
#5 Will fix it
